name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t website2 .
          docker save -o website2.tar website2

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: website2-image
          path: website2.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: website2-image

      - name: Load Docker image
        run: docker load -i website2.tar

      - name: Run tests
        run: docker run website2 echo "Tests passed!"

  
deploy:
  runs-on: self-hosted
  needs: test
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: website2-image

    - name: Check if Docker image exists
      run: ls -l website2.tar

    - name: Check Docker status
      run: docker --version && docker ps

    - name: Remove existing Docker image
      run: docker rmi website2 || true

    - name: Load Docker image
      run: docker load -i website2.tar

    - name: Deploy application
      run: |
        echo "Deploying to VM5..."
        docker stop my-website || true
        docker rm my-website || true
        docker run -d --name my-website -p 80:80 website2
