name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        run: docker build -t website .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and Remove Docker Container
        run: |
          docker stop website || true
          docker rm website || true

      - name: Run Docker Container
        run: docker run -d --name website website
